import { NextResponse } from 'next/server';
import { Groq } from 'groq-sdk';

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

export async function POST(req: Request) {
    try {
        const { text } = await req.json();

        if (!text || text.length < 50) {
            // Text is too short to reliably flag as AI-generated; pass automatically.
            return NextResponse.json({ isCheat: false, reason: "Text too short to analyze." });
        }

        const completion = await groq.chat.completions.create({
            model: "llama-3.3-70b-versatile",
            messages: [
                {
                    role: "system",
                    content: `You are an elite, strict Plagiarism and AI-Detection engine enforcing a zero-tolerance cheating policy for an engineering bootcamp. 
Your sole directive is to analyze the user's input text and detect if it was generated by an LLM (ChatGPT, Claude, etc.) rather than typed by a human.

Specifically look for:
1. Overly perfect, robotic grammar with no human "burstiness" or natural perplexity.
2. Tell-tale AI cadences ("Firstly,", "Secondly,", "Moreover", "In conclusion").
3. Unnatural density of corporate buzzwords that a junior/mid-level engineer wouldn't casually type.

Respond strictly with a pure JSON object:
{
    "isCheat": boolean,
    "confidence": number, // 0 to 100
    "reason": "Short string explaining exactly why it was flagged or cleared."
}
Only flag 'isCheat: true' if your confidence is greater than 85%. Do not return markdown blocks, just the JSON.`
                },
                {
                    role: "user",
                    content: `Analyze this text for AI generation markers:\n\n"${text}"`
                }
            ],
            temperature: 0.1,
            response_format: { type: 'json_object' }
        });

        const dataContent = completion.choices[0]?.message?.content || '{"isCheat": false}';
        const parsed = JSON.parse(dataContent);

        if (parsed.isCheat && parsed.confidence > 80) {
            return NextResponse.json({ isCheat: true, reason: parsed.reason });
        }

        return NextResponse.json({ isCheat: false, reason: "Human written" });
    } catch (error) {
        console.error("Detect Cheat API Error:", error);
        // Fail open if the API crashes so the user is not blocked
        return NextResponse.json({ isCheat: false, reason: "Detection failed, bypassed." }, { status: 200 });
    }
}
